language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '6'
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run travis-deploy-once "npm run deploy-docs"
  - npm run travis-deploy-once "npm run semantic-release"
